name : print hi

on :
  pull_request:
    branches:
     - main

  jobs:
     print_hi:
       run-on: ubuntu-latest:
          stpes:
          - uses : actions/chechout@v4
           -run :  echo "hi"
